[book]
title = "ClamAV Documentation"
description = "An open source malware detection toolkit and antivirus engine."
authors = ["Cisco Systems, Inc."]
language = "en"
src = "src"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/"
theme = "theme"
default-theme = "clamav"
preferred-dark-theme  = "clamav"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
