name: Deploy
on:
  push:
    branches:
      - main

env:
  CNAME: docs.clamav.net

jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust (rustup)
      run: rustup update stable --no-self-update && rustup default stable
    - name: Install mdBook
      run: cargo install mdbook
    - name: Build book
      run: mdbook build .
    - name: Deploy to GitHub
      env:
        GITHUB_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        touch book/.nojekyll
        echo ${{ env.CNAME }} > book/CNAME
        rustc deploy.rs -o /tmp/deploy
        cd book
        /tmp/deploy
